[project]
name = "jaxfun"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mikael Mortensen" },
    { name = "August Femtehjell" }
]
requires-python = ">=3.10"
dependencies = [
    "jax>=0.4.36",
    "matplotlib>=3.9.3",
    "pytest>=8.3.4",
    "ruff>=0.9.4",
    "sympy>=1.13.3",
    "flax>=0.10.1"
]

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipython>=8.37.0",
    "soap-jax",
]

[tool.uv.sources]
soap-jax = { git = "https://github.com/haydn-jones/SOAP_JAX" }
